/**
 * "My Series" library types — series added by an admin from a single IMDb
 * ID, where every TV episode's embed URL is generated by string-replacing
 * the provider template ({id}/{s}/{e}).
 */

export interface SavedEpisode {
    number: number;
    title?: string;
    /** Jikan thumbnail (16:9) when metadata was available. */
    thumbnail?: string;
    /**
     * Embed URL generated for THIS episode (template with {id}/{s}/{e}
     * replaced). Stored per-episode so the player just renders it —
     * never recomputed from stale state.
     */
    embedUrl: string;
}

export interface SavedSeason {
    /** Admin season number — also the {s} used in the embed URL. */
    number: number;
    /** AniList season title, when metadata was available. */
    name?: string;
    /** MAL id of this season (used for Jikan episode titles/thumbnails). */
    malId?: number;
    episodes: SavedEpisode[];
}

export interface SavedSeries {
    /** Stable id — the (lower-cased) IMDb ID the series was added with. */
    id: string;
    name: string;
    /** IMDb ID, lower-cased (tt1234567). */
    imdbId: string;
    /** 'nxsha' | 'nhd' | 'custom' */
    providerId: string;
    /** Custom template when providerId === 'custom'. */
    template?: string;
    poster?: string;
    banner?: string;
    description?: string;
    genres?: string[];
    year?: string;
    seasons: SavedSeason[];
    addedAt: number;
}

/** What an admin types into the "Add Series" form. */
export interface SeriesDraft {
    name: string;
    imdbId: string;
    seasons: number;
    episodesPerSeason: number;
    providerId: string;
    /** Required when providerId === 'custom'. */
    template?: string;
}
