import React, { useMemo, useState } from 'react';
import {
    ActivityIndicator,
    KeyboardAvoidingView,
    Platform,
    Pressable,
    ScrollView,
    StyleSheet,
    Text,
    TextInput,
    View,
} from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { SafeImage } from '@/components/SafeImage';
import { WEB_NAV_HEIGHT } from '@/components/WebNavBar';
import { useMySeries } from '@/hooks/useMySeries';
import { buildSeries, totalEpisodeCount } from '@/services/seriesBuilder';
import { fetchSeriesMetadata } from '@/services/seriesMetadata';
import {
    CUSTOM_PROVIDER_ID,
    PROVIDERS,
    buildEmbedUrl,
    getProvider,
    isValidImdbId,
    providerLabel,
    templateError,
} from '@/services/embedProviders';
import { SavedSeries, SeriesDraft } from '@/types/series';

/**
 * Admin: add a series from a single IMDb ID.
 *
 *   name + IMDb ID + seasons + episodes/season + provider (preset or
 *   custom template)  ->  every episode's embed URL is generated by
 *   string-replacing the template ({id}/{s}/{e}) and stored per episode.
 *
 * Metadata (poster/banner/genres/seasons) comes keyless from AniList,
 * episode titles/thumbnails from Jikan — both best-effort.
 */
export default function AdminScreen() {
    const router = useRouter();
    const { series, addSeries, removeSeries } = useMySeries();

    const [name, setName] = useState('');
    const [imdbId, setImdbId] = useState('');
    const [seasons, setSeasons] = useState('1');
    const [episodes, setEpisodes] = useState('12');
    const [providerId, setProviderId] = useState('nxsha');
    const [customTemplate, setCustomTemplate] = useState('');

    const [saving, setSaving] = useState(false);
    const [step, setStep] = useState('');
    const [error, setError] = useState('');
    const [saved, setSaved] = useState<SavedSeries | null>(null);

    const template = useMemo(() => {
        if (providerId === CUSTOM_PROVIDER_ID) return customTemplate.trim();
        return getProvider(providerId)?.template ?? '';
    }, [providerId, customTemplate]);

    const imdbError = useMemo(() => {
        const v = imdbId.trim();
        if (!v) return '';
        return isValidImdbId(v) ? '' : 'IMDb ID must look like tt1234567 (tt + digits).';
    }, [imdbId]);

    const tplError = useMemo(
        () => (providerId === CUSTOM_PROVIDER_ID ? templateError(customTemplate) : ''),
        [providerId, customTemplate],
    );

    const seasonNum = Math.floor(Number(seasons));
    const episodeNum = Math.floor(Number(episodes));
    const countError =
        !Number.isFinite(seasonNum) || seasonNum < 1
            ? 'Seasons must be at least 1.'
            : !Number.isFinite(episodeNum) || episodeNum < 1
                ? 'Episodes per season must be at least 1.'
                : '';

    const canSave =
        !saving &&
        name.trim().length > 1 &&
        !imdbError &&
        !tplError &&
        !countError;

    const previewUrl = canSave
        ? buildEmbedUrl(template, { id: imdbId.trim().toLowerCase(), s: 1, e: 1 })
        : '';

    const resetForm = () => {
        setName('');
        setImdbId('');
        setSeasons('1');
        setEpisodes('12');
        setProviderId('nxsha');
        setCustomTemplate('');
        setError('');
        setSaved(null);
    };

    const handleSave = async () => {
        if (!canSave) return;
        const draft: SeriesDraft = {
            name: name.trim(),
            imdbId: imdbId.trim().toLowerCase(),
            seasons: seasonNum,
            episodesPerSeason: episodeNum,
            providerId,
            template: customTemplate.trim(),
        };

        setSaving(true);
        setError('');
        setStep('Searching AniList for poster, banner & season chain…');

        let seriesObj: SavedSeries;
        try {
            // Best-effort: metadata failure never blocks saving.
            const metadata = await fetchSeriesMetadata(draft);

            setStep('Generating embed URLs for every episode…');
            seriesObj = buildSeries(draft, metadata);
            addSeries(seriesObj);
            setSaved(seriesObj);
        } catch (e) {
            setError(
                e instanceof Error ? e.message : 'Could not save the series.',
            );
        } finally {
            setSaving(false);
            setStep('');
        }
    };

    return (
        <View style={styles.container}>
            <Stack.Screen options={{ headerShown: false }} />
            <KeyboardAvoidingView
                behavior={Platform.OS === 'ios' ? 'padding' : undefined}
                style={styles.flex}
            >
                <ScrollView
                    style={styles.flex}
                    contentContainerStyle={[
                        styles.content,
                        Platform.OS === 'web' && {
                            paddingTop: WEB_NAV_HEIGHT + 28,
                            paddingBottom: 80,
                        },
                    ]}
                    showsVerticalScrollIndicator={false}
                >
                    <View style={styles.header}>
                        <Pressable
                            style={({ hovered }: any) => [
                                styles.backBtn,
                                hovered && styles.backBtnHover,
                            ]}
                            onPress={() => router.back()}
                        >
                            <Ionicons name="chevron-back" size={20} color="#fff" />
                        </Pressable>
                        <View style={styles.headerText}>
                            <Text style={styles.title}>Add Series</Text>
                            <Text style={styles.subtitle}>
                                Play any TV episode from a single IMDb ID —
                                powered by Nxsha (Hindi) & NHD embeds.
                            </Text>
                        </View>
                    </View>

                    {saved ? (
                        <View style={styles.successCard}>
                            <Ionicons name="checkmark-circle" size={40} color="#46d369" />
                            <Text style={styles.successTitle}>
                                {saved.name} added
                            </Text>
                            <Text style={styles.successSub}>
                                {saved.seasons.length} season
                                {saved.seasons.length > 1 ? 's' : ''} ·{' '}
                                {totalEpisodeCount(saved)} episodes ·{' '}
                                {providerLabel(saved)}
                            </Text>
                            {saved.poster ? (
                                <SafeImage
                                    source={{ uri: saved.poster }}
                                    style={styles.successPoster}
                                    fallbackLabel={saved.name}
                                />
                            ) : null}
                            <View style={styles.successBtns}>
                                <Pressable
                                    style={styles.successPrimary}
                                    onPress={() =>
                                        router.push({
                                            pathname: '/series/[id]',
                                            params: { id: saved.id },
                                        })
                                    }
                                >
                                    <Ionicons name="play" size={16} color="#000" />
                                    <Text style={styles.successPrimaryText}>
                                        Open series
                                    </Text>
                                </Pressable>
                                <Pressable style={styles.successGhost} onPress={resetForm}>
                                    <Text style={styles.successGhostText}>
                                        Add another
                                    </Text>
                                </Pressable>
                            </View>
                        </View>
                    ) : (
                        <View style={styles.form}>
                            <Field label="Series / anime name">
                                <TextInput
                                    style={styles.input}
                                    value={name}
                                    onChangeText={setName}
                                    placeholder="e.g. Sousou no Frieren"
                                    placeholderTextColor="#666"
                                    autoCapitalize="words"
                                />
                            </Field>

                            <Field label="IMDb ID" error={imdbError}>
                                <TextInput
                                    style={[
                                        styles.input,
                                        imdbError !== '' && styles.inputError,
                                    ]}
                                    value={imdbId}
                                    onChangeText={setImdbId}
                                    placeholder="tt1234567"
                                    placeholderTextColor="#666"
                                    autoCapitalize="none"
                                    autoCorrect={false}
                                />
                            </Field>

                            <View style={styles.row}>
                                <View style={styles.rowCol}>
                                    <Field label="Seasons">
                                        <TextInput
                                            style={styles.input}
                                            value={seasons}
                                            onChangeText={setSeasons}
                                            keyboardType="number-pad"
                                            placeholder="1"
                                        />
                                    </Field>
                                </View>
                                <View style={styles.rowCol}>
                                    <Field label="Episodes / season">
                                        <TextInput
                                            style={styles.input}
                                            value={episodes}
                                            onChangeText={setEpisodes}
                                            keyboardType="number-pad"
                                            placeholder="12"
                                        />
                                    </Field>
                                </View>
                            </View>
                            {countError ? (
                                <Text style={styles.errorText}>{countError}</Text>
                            ) : null}

                            <Field label="Embed provider">
                                <View style={styles.providerList}>
                                    {PROVIDERS.map(p => (
                                        <Pressable
                                            key={p.id}
                                            style={({ hovered }: any) => [
                                                styles.providerRow,
                                                providerId === p.id &&
                                                    styles.providerRowActive,
                                                hovered && styles.providerRowHover,
                                            ]}
                                            onPress={() => setProviderId(p.id)}
                                        >
                                            <View
                                                style={[
                                                    styles.radio,
                                                    providerId === p.id &&
                                                        styles.radioActive,
                                                ]}
                                            >
                                                {providerId === p.id ? (
                                                    <Ionicons
                                                        name="checkmark"
                                                        size={11}
                                                        color="#000"
                                                    />
                                                ) : null}
                                            </View>
                                            <Text style={styles.providerName}>
                                                {p.name}
                                            </Text>
                                            <Text
                                                style={styles.providerTemplate}
                                                numberOfLines={1}
                                            >
                                                {p.template}
                                            </Text>
                                        </Pressable>
                                    ))}

                                    <Pressable
                                        style={({ hovered }: any) => [
                                            styles.providerRow,
                                            providerId === CUSTOM_PROVIDER_ID &&
                                                styles.providerRowActive,
                                            hovered && styles.providerRowHover,
                                        ]}
                                        onPress={() => setProviderId(CUSTOM_PROVIDER_ID)}
                                    >
                                        <View
                                            style={[
                                                styles.radio,
                                                providerId === CUSTOM_PROVIDER_ID &&
                                                    styles.radioActive,
                                            ]}
                                        >
                                            {providerId === CUSTOM_PROVIDER_ID ? (
                                                <Ionicons
                                                    name="checkmark"
                                                    size={11}
                                                    color="#000"
                                                />
                                            ) : null}
                                        </View>
                                        <Text style={styles.providerName}>
                                            Custom template
                                        </Text>
                                        <Text style={styles.providerTemplate}>
                                            Nxsha domains change sometimes
                                            (e.g. web.nxsha.app)
                                        </Text>
                                    </Pressable>
                                </View>
                            </Field>

                            {providerId === CUSTOM_PROVIDER_ID ? (
                                <Field
                                    label="Custom embed URL template"
                                    error={tplError}
                                >
                                    <TextInput
                                        style={[
                                            styles.input,
                                            styles.mono,
                                            tplError !== '' && styles.inputError,
                                        ]}
                                        value={customTemplate}
                                        onChangeText={setCustomTemplate}
                                        placeholder="https://web.nxsha.app/embed/tv/{id}/{s}/{e}?lang=hi"
                                        placeholderTextColor="#666"
                                        autoCapitalize="none"
                                        autoCorrect={false}
                                        multiline
                                        numberOfLines={2}
                                    />
                                    <Text style={styles.hintText}>
                                        Must contain all three placeholders:
                                        {'  '}{'{id}'} = IMDb ID, {'  '}{'{s}'} =
                                        season, {'  '}{'{e}'} = episode.
                                    </Text>
                                </Field>
                            ) : null}

                            {previewUrl ? (
                                <View style={styles.preview}>
                                    <Text style={styles.previewLabel}>
                                        Preview — S1E1
                                    </Text>
                                    <Text
                                        style={[styles.mono, styles.previewUrl]}
                                        numberOfLines={2}
                                    >
                                        {previewUrl}
                                    </Text>
                                </View>
                            ) : null}

                            {error ? (
                                <Text style={styles.errorText}>{error}</Text>
                            ) : null}

                            <Pressable
                                style={({ hovered }: any) => [
                                    styles.saveBtn,
                                    canSave && styles.saveBtnEnabled,
                                    canSave && hovered && styles.saveBtnHover,
                                ]}
                                onPress={handleSave}
                                disabled={!canSave}
                            >
                                {saving ? (
                                    <ActivityIndicator size="small" color="#fff" />
                                ) : (
                                    <Ionicons
                                        name="cloud-upload-outline"
                                        size={17}
                                        color="#fff"
                                    />
                                )}
                                <Text style={styles.saveBtnText}>
                                    {saving
                                        ? 'Adding…'
                                        : 'Add series & generate embed URLs'}
                                </Text>
                            </Pressable>
                            {saving ? (
                                <Text style={styles.stepText}>{step}</Text>
                            ) : null}
                        </View>
                    )}

                    {series.length > 0 ? (
                        <View style={styles.library}>
                            <Text style={styles.libraryTitle}>Your series</Text>
                            {series.map(s => (
                                <View key={s.id} style={styles.libraryRow}>
                                    <SafeImage
                                        source={{ uri: s.poster || s.banner || '' }}
                                        style={styles.libraryPoster}
                                        fallbackLabel={s.name}
                                    />
                                    <View style={styles.libraryInfo}>
                                        <Text
                                            style={styles.libraryName}
                                            numberOfLines={1}
                                        >
                                            {s.name}
                                        </Text>
                                        <Text
                                            style={styles.libraryMeta}
                                            numberOfLines={1}
                                        >
                                            {s.imdbId} · {s.seasons.length} S ·{' '}
                                            {totalEpisodeCount(s)} EP ·{' '}
                                            {providerLabel(s)}
                                        </Text>
                                    </View>
                                    <Pressable
                                        style={({ hovered }: any) => [
                                            styles.libraryOpen,
                                            hovered && styles.libraryOpenHover,
                                        ]}
                                        onPress={() =>
                                            router.push({
                                                pathname: '/series/[id]',
                                                params: { id: s.id },
                                            })
                                        }
                                    >
                                        <Ionicons name="play" size={16} color="#000" />
                                    </Pressable>
                                    <Pressable
                                        style={({ hovered }: any) => [
                                            styles.libraryDelete,
                                            hovered && styles.libraryDeleteHover,
                                        ]}
                                        onPress={() => removeSeries(s.id)}
                                        accessibilityLabel={`Remove ${s.name}`}
                                    >
                                        <Ionicons
                                            name="trash-outline"
                                            size={16}
                                            color="#e0e0e0"
                                        />
                                    </Pressable>
                                </View>
                            ))}
                        </View>
                    ) : null}
                </ScrollView>
            </KeyboardAvoidingView>
        </View>
    );
}

function Field({
    label,
    error,
    children,
}: {
    label: string;
    error?: string;
    children: React.ReactNode;
}) {
    return (
        <View style={styles.field}>
            <Text style={styles.label}>{label}</Text>
            {children}
            {error ? <Text style={styles.errorText}>{error}</Text> : null}
        </View>
    );
}
const styles = StyleSheet.create({
    flex: { flex: 1 },
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    content: {
        width: '100%',
        maxWidth: 760,
        alignSelf: 'center',
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 60,
        gap: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        marginBottom: 6,
    },
    backBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    backBtnHover: {
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    headerText: {
        flex: 1,
    },
    title: {
        color: '#fff',
        fontSize: 28,
        fontWeight: '800',
    },
    subtitle: {
        color: '#9a9a9a',
        fontSize: 12.5,
        marginTop: 3,
        lineHeight: 17,
    },
    form: {
        gap: 16,
        backgroundColor: '#141414',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#232323',
        padding: 18,
    },
    field: {
        gap: 7,
    },
    label: {
        color: '#cfcfcf',
        fontSize: 12.5,
        fontWeight: '700',
    },
    input: {
        backgroundColor: '#1f1f1f',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#2e2e2e',
        color: '#fff',
        fontSize: 14.5,
        paddingHorizontal: 12,
        paddingVertical: 11,
    },
    inputError: {
        borderColor: '#E50914',
    },
    mono: {
        fontFamily: 'monospace',
        fontSize: 12.5,
    },
    row: {
        flexDirection: 'row',
        gap: 12,
    },
    rowCol: {
        flex: 1,
    },
    errorText: {
        color: '#ff6b6b',
        fontSize: 11.5,
        fontWeight: '600',
        marginTop: 6,
    },
    hintText: {
        color: '#8a8a8a',
        fontSize: 11.5,
        lineHeight: 16,
        marginTop: 4,
    },
    providerList: {
        gap: 8,
    },
    providerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: '#1f1f1f',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#2e2e2e',
        paddingHorizontal: 12,
        paddingVertical: 11,
    },
    providerRowHover: {
        borderColor: '#444',
    },
    providerRowActive: {
        borderColor: '#E50914',
        backgroundColor: 'rgba(229,9,20,0.08)',
    },
    radio: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 2,
        borderColor: '#555',
        alignItems: 'center',
        justifyContent: 'center',
    },
    radioActive: {
        backgroundColor: '#fff',
        borderColor: '#fff',
    },
    providerName: {
        color: '#fff',
        fontSize: 13.5,
        fontWeight: '700',
        flexShrink: 0,
    },
    providerTemplate: {
        color: '#7c7c7c',
        fontSize: 10.5,
        flex: 1,
        marginLeft: 6,
    },
    preview: {
        backgroundColor: '#0f0f0f',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#262626',
        padding: 10,
        gap: 5,
    },
    previewLabel: {
        color: '#8a8a8a',
        fontSize: 10.5,
        fontWeight: '800',
        letterSpacing: 0.6,
        textTransform: 'uppercase',
    },
    previewUrl: {
        color: '#9ecbff',
        lineHeight: 16,
    },
    saveBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#3a3a3a',
        borderRadius: 10,
        paddingVertical: 13,
        opacity: 0.7,
    },
    saveBtnEnabled: {
        backgroundColor: '#E50914',
        opacity: 1,
    },
    saveBtnHover: {
        backgroundColor: '#f6121d',
    },
    saveBtnText: {
        color: '#fff',
        fontSize: 14.5,
        fontWeight: '800',
    },
    stepText: {
        color: '#8a8a8a',
        fontSize: 12,
        textAlign: 'center',
    },
    successCard: {
        backgroundColor: '#141414',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#1f3a26',
        padding: 22,
        alignItems: 'center',
        gap: 8,
    },
    successTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '800',
    },
    successSub: {
        color: '#9a9a9a',
        fontSize: 13,
    },
    successPoster: {
        width: 110,
        aspectRatio: 2 / 3,
        borderRadius: 8,
        marginTop: 8,
    },
    successBtns: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 10,
    },
    successPrimary: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#fff',
        borderRadius: 999,
        paddingHorizontal: 18,
        paddingVertical: 10,
    },
    successPrimaryText: {
        color: '#000',
        fontSize: 13,
        fontWeight: '800',
    },
    successGhost: {
        borderRadius: 999,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.3)',
        paddingHorizontal: 16,
        paddingVertical: 10,
    },
    successGhostText: {
        color: '#e5e5e5',
        fontSize: 13,
        fontWeight: '700',
    },
    library: {
        gap: 10,
    },
    libraryTitle: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '800',
        marginTop: 10,
    },
    libraryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: '#141414',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#232323',
        padding: 10,
    },
    libraryPoster: {
        width: 44,
        height: 66,
        borderRadius: 6,
        backgroundColor: '#222',
    },
    libraryInfo: {
        flex: 1,
        gap: 3,
    },
    libraryName: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '700',
    },
    libraryMeta: {
        color: '#8a8a8a',
        fontSize: 11,
    },
    libraryOpen: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    libraryOpenHover: {
        backgroundColor: '#e5e5e5',
    },
    libraryDelete: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: 'rgba(255,255,255,0.08)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    libraryDeleteHover: {
        backgroundColor: 'rgba(229,9,20,0.25)',
    },
});
